#include <iostream>
#include <iomanip>
#include <string>
#include <vector>
/**
 * @brief Prints a stylized header to the console.
 * @details Wraps the provided text in rows of '=' characters for visual separation.
 * @param text The string to be displayed within the header.
 */
void print_header(const std::string& text) {
    std::cout << std::setfill('=') << std::setw(60) << "" << "\n";  // line of '='
    std::cout << std::setfill(' ') << std::setw(60) << std::left << text << "\n";
    std::cout << std::setfill('=') << std::setw(60) << "" << "\n";
	std::cout << std::setfill(' '); // reset fill to space
}


/**
 * @brief Prints a 1D vector of floats in a formatted horizontal array.
 * @details Output format is `[ val1 val2 ... ]` with each value fixed to 2 decimal
 * places and a width of 6 characters for alignment.
 * @param vec The vector of floats to display.
 */
void print_vector(const std::vector<float>& vec) {
    if (vec.empty()) {
        std::cout << "[ ]\n";
        return;
	}
    std::cout << "[ ";

    for (size_t i = 0; i < vec.size(); ++i) {
        std::cout << std::fixed << std::setprecision(2) << std::setw(6) << vec[i];

        /*if (i < vec.size() - 1) {
            std::cout << ", ";
        }*/
    }

    std::cout << " ]\n";
}

/**
 * @brief Displays a comparison between inputs, targets, and actual model predictions.
 * @details Useful for visually inspecting model performance on a small sample of data.
 * @param feedforward_input The original feature data.
 * @param target_output The ground-truth labels.
 * @param feedforward_output The predictions generated by the NeuralNetwork.
 * @param sample_count The maximum number of samples to print (defaults to 5).
 */
void print_feedforward_output(const std::vector<std::vector<float>>& feedforward_input,
    const std::vector<std::vector<float>>& target_output,
    const std::vector<std::vector<float>>& feedforward_output,
    size_t sample_count = 5) {
	print_header(" Feedforward Output ");
    size_t samples_nb = std::min(feedforward_input.size(), sample_count);
    for (size_t i = 0; i < samples_nb; ++i) {
        std::cout << "Sample " << i + 1 << ":\n";
        std::cout << "  Input:    ";
        print_vector(feedforward_input[i]);
        std::cout << "  Target:   ";
        print_vector(target_output[i]);
        std::cout << "  Feedforward prediction:   ";
        print_vector(feedforward_output[i]);
        std::cout << "\n";
	}
}