#pragma once
#ifndef DISPLAY_H
#define DISPLAY_H

#include <string>
/** @file display.h
 * @brief Header file for display functions.
 */

// Prints a main header
/**
 * @brief Prints a stylized header to the console.
 * @details Wraps the provided text in rows of '=' characters for visual separation.
 * @param text The string to be displayed within the header.
 */
void print_header(const std::string& text);
/**
 * @brief Prints a 1D vector of floats in a formatted horizontal array.
 * @details Output format is `[ val1 val2 ... ]` with each value fixed to 2 decimal
 * places and a width of 6 characters for alignment.
 * @param vec The vector of floats to display.
 */
void print_vector(const std::vector<float>& vec);

/**
 * @brief Displays a comparison between inputs, targets, and actual model predictions.
 * @details Useful for visually inspecting model performance on a small sample of data.
 * @param feedforward_input The original feature data.
 * @param target_output The ground-truth labels.
 * @param feedforward_output The predictions generated by the NeuralNetwork.
 * @param sample_count The maximum number of samples to print (defaults to 5).
 */
void print_feedforward_output(const std::vector<std::vector<float>>& feedforward_input,
								const std::vector<std::vector<float>>& target_output,
								const std::vector<std::vector<float>>& feedforward_output,
								const size_t sample_count = 5);
#endif 